### ISSUE TITLE
UPM Invalid Argument: Temperature: mraa_aio_init() failed, invalid pin?

### ISSUE THREAD

**Issue by trajkd** [eclipse/upm#699]
I’m getting

```
Traceback (most recent call last):
File "/usr/src/app/grovetemp.py", line 28, in <module>
temp = upm.Temperature(0)
File "/usr/local/lib/python2.7/site-packages/upm/pyupm_temperature.py", line 106, in __init__
this = _pyupm_temperature.new_Temperature(pin, scale, r0, b)
UPM Invalid Argument: Temperature: mraa_aio_init() failed, invalid pin?
```
even though I have: 
```
from upm import pyupm_temperature as upm
temp = upm.Temperature(0)
```

in temperature.py and I’ve connected the sensor to A0.
What might be going on?

**Comment by trajkd** [comment]
The board is an Intel Edison Arduino with the Grove Temperature v1.1 sensor.

**Comment by trajkd** [comment]
The Intel Edison board is running balena OS.
